#!/bin/bash
if [ "$1" = "" ]; then
    echo "Run name is missing. Exiting"
        exit 1
fi
export PATH=${PATH}:/cs/icore/joshua.moss/scripts/btseq
Rscript /cs/icore/joshua.moss/scripts/btseq/btseq_setup.R
#source /cs/icore/joshua.moss/scripts/btseq/btseq_setup
jid1=$(sbatch --job-name=gr get_reads $1)
jid1=${jid1:20}
jid2=$(sbatch --job-name=pt --dependency=afterany:$jid1 --output=prep_trim.out btseq_prepare_trim)
jid2=${jid2:20}
jid3=$(sbatch --job-name=pa --dependency=afterany:$jid2 --output=prep_aln.out btseq_prepare_align)
jid3=${jid3:20}
sbatch --dependency=afterany:$jid3 --job-name=run --output=run.out btseq_run
