#!/bin/bash
if [ "$1" = "" ]; then
    echo "Run name is missing. Exiting"
        exit 1
fi
export PATH=${PATH}:/cs/icore/joshua.moss/scripts/btseq
Rscript /cs/icore/joshua.moss/scripts/btseq/btseq_setup.R
#source /cs/icore/joshua.moss/scripts/btseq/btseq_setup
jid1=$(sbatch --job-name=gr get_reads $1)
jid1=${jid1:(-7)}
jid2=$(sbatch --job-name=pt --dependency=afterok:$jid1 --output=prep_trim.out btseq_prepare_trim)
jid2=${jid2:(-7)}
jid3=$(sbatch --job-name=pa --dependency=afterok:$jid2 --output=prep_aln.out btseq_prepare_align)
jid3=${jid3:(-7)}
sbatch --dependency=afterok:$jid3 --job-name=run --output=run.out btseq_run
