#!/bin/bash
jidt=""
for f in trim_galore/Run/A*q; do
  jid=$(sbatch --job-name=trim --output=${f}.out --mem=4GB --cpus-per-task=3 --time=5:00:00 $f)
  jid=${jid:20}
  jidt="${jidt}:${jid}"
done
jida=""
for f in Run/Sample*q; do
  jid=$(sbatch --job-name=aln --dependency=afterok$jidt --output=${f}.out --mem=4GB --cpus-per-task=5 --time=5:00:00 $f)
  jid=${jid:20}
  jida="${jida}:${jid}"
done
jida2=""
n=$(ls -1 *fa | wc -l)
nums=$(seq 1 $n)
for i in $nums; do
  sum_file=Sample_$i/Output/*summary 
  sum_file_exists=$(ls -1 $sum_file 2>/dev/null | wc -l)
  if [ $sum_file_exists = "0" ]
  then 
  echo Sample $i missing. Realigning this sample
#  f=Run/Sample_${i}.q
#  jid=$(sbatch --job-name=aln --dependency=afterany$jida --output=Run/$f.out --mem=4GB --cpus-per-task=5 --time=5:00:00 $f)
#  jid=${jid:20}
#  jida2="${jida}:${jid}"
  fi
done
jida3="${jida}:${jida2}"
sbatch --dependency=afterany$jida3 --job-name=sum --output=sum.out btseq_summary
