#!/bin/bash
jidt=""
for f in trim_galore/Run/A*q; do
  jid=$(sbatch --job-name=trim --output=${f}.out --mem=4GB --cpus-per-task=3 --time=5:00:00 $f)
  sleep 3
  jid=${jid:20}
  jidt="${jidt}:${jid}"
done
jida=""
for f in Run/Sample*q; do
  jid=$(sbatch --job-name=aln --dependency=afterany$jidt --output=${f}.out --mem=4GB --cpus-per-task=5 --time=5:00:00 $f)
  sleep 3
  jid=${jid:20}
  jida="${jida}:${jid}"
done
sbatch --dependency=afterany$jida --job-name=sum --output=sum.out btseq_summary
